repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        name: Strip output from Jupyter notebooks
        description: This hook strips the output from Jupyter notebooks to avoid unnecessary diffs in version control.
        files: \.ipynb$
