look_back_days: [10, 30, 90, 180, 540, 1620]

plotly_config:
  displayModeBar: false

page_config:
  initial_sidebar_state: expanded
  page_icon: 📈
  layout: wide
  menu_items:
    "Get Help": "mailto: weiyang2048@gmail.com"
    "Report a bug": "https://github.com/weiyang2048/Investments"
    "About": |
      email: weiyang2048@gmail.com

      personal website: [noWei.us](https://www.noWei.us)

style_string: |
  <style>
  [data-testid="stSidebar"][aria-expanded="true"] {
      max-width: 3vw;
      z-index: 1000001!important;
  }
  .stAppToolbar {
    padding:0!important;
    margin:0!important;s
    font-size: 1px!important;
    background-color: rgba(30, 30, 30, 0.5);
    z-index: -1000!important;
    position: relative!important;
  }
  .stMainBlockContainer {
    padding-left: 1%;
    padding-right: 1%;
    padding-top: 2%;
    background-color: black;
  }
  button {
    z-index: 1000000!important;
  }
  h1 {
    display: block;
    text-align: center;
    z-index: 1000000!important;
  }
  h1, p {
    margin:0;
    padding:0;
  }

  #homepage-link {
    margin-top: 50vh!important;
  }
   #homepage-link,#linkedin-link {
    display: block;
    margin-bottom: 10px!important;
    margin-left: auto!important;
    margin-right: auto!important;
    text-align: center!important;
    font-size: 12px;
    color: white;
    padding: 5px!important;
    background-color: black;
    border-radius: 51px;
    border: 1px solid #666;
    text-decoration: none;
    cursor: pointer;
    transition: all 0.3s ease;
    &:hover {
      scale: 1.05;
      color: black;
      background-color: white;
    }
  }

  .stMarkdown {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }

  /*
  Headers
  */

  h1{
    color: white!important;
  }
  .stMarkdown h2 {
      color: #1f77b4;
      border-bottom: 2px solid #1f77b4;
      padding-bottom: 5px;
  }
  .stMarkdown h3 {
      color: #ff7f0e;
      margin-top: 20px;
  }
  .stMarkdown a {
      color: #2e86ab;
      text-decoration: none;
  }
  .stMarkdown a:hover {
      text-decoration: underline;
      color: #1f77b4;
  }
  .stColumn .stVerticalBlock > * {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: auto!important;
    padding: 0!important;
  }

  /*
  folium map
  */
  #map_div {
    width: 100%!important;
    height: 100%!important;
  }
  </style>
