look_back_days: [10, 30, 90, 180, 540, 1620]

page_config:
  initial_sidebar_state: expanded
  page_icon: 📈
  layout: wide
  menu_items:
    "Get Help": "mailto: weiyang2048@gmail.com"
    "Report a bug": "https://github.com/weiyang2048/Investments"
    "About": |
      email: weiyang2048@gmail.com

      personal website: [noWei.us](https://www.noWei.us)

style_css_url: conf/style_conf/styles.css
