# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
[theme]
primaryColor = "lightgreen"
backgroundColor = "black"
secondaryBackgroundColor = 'darkgray'
textColor = "white"
font = "cool-font, fallback-cool-font, sans-serif"
dataframeHeaderBackgroundColor = "rgba(50, 50, 50, 0.5)"
baseRadius = "full"
[theme.sidebar]
primaryColor = "crimson"
backgroundColor = "snow"
secondaryBackgroundColor = "royalblue"
textColor = "black"
borderColor = "purple"
baseRadius = "none"

[client]
# toolbarMode = "minimal"

[ui]
# hideTopBar = true
