# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
[theme]
base = "light"
primaryColor = "lightgreen"
backgroundColor = "black"
secondaryBackgroundColor = "snow"
font = "cool-font, fallback-cool-font, sans-serif"

[client]
# toolbarMode = "minimal"

[ui]
# hideTopBar = true
